services:

  reverse_proxy:
    image: nginx:stable
    restart: always
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV="production"
    command: serve -s dist -p 3000

  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: fastapi run samplescape/main.py --proxy-headers --port 8000
